version: '3'
services:
  app:
    container_name: appcontainer
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    # ports from container exposed to the docker machine and the guest machine
    ports:
      # 80 on the host, 8080 on the guest. Websever listens on 8080
      - "80:9000" # http
      - "443:443" # https
    # file with environment declarations for the container
    env_file:
      - docker/app/.env
    working_dir: /var/www/src  
    # sync workspace folder with /go
    volumes:
     - ./src/:/var/www/src
    # Link to containers in another service
    depends_on:
      - mysql
  mysql:
    container_name: mysqlcontainer
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      - "33061:3306"
    restart: always
    environment:
      MYSQL_DATABASE: cmc
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/mysql/dbdata/:/var/lib/mysql