version: '1'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    # ports from container exposed to the docker machine and the guest machine
    ports:
      # 80 on the host, 8080 on the guest. Websever listens on 8080
      - "80:9000" # http
      - "443:443" # https
    # file with environment declarations for the container
    env_file:
      - docker/app/.env
    working_dir: /var/www/src  
    # Link to containers in another service
    links:
      - mysql
    # sync workspace folder with /go
    volumes:
     - ./src/:/var/www/src
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    # sync folders. MySQL data is stored outside container so that rebuilding doesn't clear db.
    # folder is at workspace root.
    volumes:
      - ./docker/mysql/dbdata:/var/lib/mysql